---
title: "CodeBook for Getting and Cleaning Data Course Project"
author: "Vern"
date: "1/19/2020"
output:
  html_document:
    keep_md: yes
---


The run_analysis.R script downloads the dataset and performs the data preparation and output as required in the assignment steps, detailed below.

0. Download and extract the data. Not part of the assignment, but helpful to have here anyway.
   * Check to see if the "data.table" package is installed, since this script relies on it.
   * Check to see if the "plyr" package is installed, since this script relies on it.
   * Check to see if the "dplyr" package is installed, since this script relies on it.
   * Check to see if a subdirectory exists for this project. If not, create it.
   * Define the zip file name on the UCI server.
   * Define the destination filename. Does not match the above filename from UCI.
   * Define the full path for the zip file.
   * Download the zip file from the UCI repository, and save it to the project subdirectory.
   * Define the directory for where the top level extracted files should go.
   * Define the directory where the extracted project files will be automatically placed. The folder in the zipped file is already named "UCI HAR Dataset".
   * Unzip the file, if it doesn't already exist.

1. Merges the training and the test sets to create one data set.
   a. Column labels for use later
      * Reads the Feature Names into the variable 'featureNames'. There are 561 features. File is "features.txt".
      * Show the duplicated column names, which need to be corrected.
      * Adding a 3rd column with a combination of featurename and index, since there are 42 triplicate column names in this dataset.
      *   Duplicated columns names won't work with dplyr select for column names, which is needed later on.
      *   This extra information will be removed towards the end of this process, and the separater/delimiter will be used in that process.
      * Reads the Activities into the variable 'activityLabels'. There are 6 activity labels. File is "activity_labels.txt".
   b. Test Data
      * Read the Test data into tables. Files are: 'X_test.txt', 'y_test.txt', 'subject_test.txt', in the 'test' folder.
      * Rename the columns in the test_feature_data table with the feature names from the 'newname' column in the featureNames table, and transform that column into 561 columns, so that they match up correctly.
      * Add a source column so that I can keep track of where the data came from: test vs train. This step is not required for this project.
      * Rename the single column in each of the tables for activity and subject.
      * Merge (by columns) all 3 tables for Test. All tables have the same number of observations (10299).
   c. Train Data
      * Read the Train data into tables. Files are: 'X_train.txt', 'y_train.txt', 'subject_train.txt', in the 'train' folder.
      * Rename the columns in the test_feature_data table with the feature names from the 'newname' column in the featureNames table, and transform that column into 561 columns, so that they match up correctly.
      * Add a source column so that I can keep track of where the data came from: test vs train. This step is not required for this project.
      * Rename the single column in each of the tables for activity and subject.
      * Merge (by columns) all 3 tables for Train. All tables have the same number of observations (10299).
   d. Merged Data
      * Merge (by Rows) the Test data and the Train data.
      
   * The column names at this point:
   
  [1] "datasource"                               "tBodyAcc-mean()-X_1"                     
  [3] "tBodyAcc-mean()-Y_2"                      "tBodyAcc-mean()-Z_3"                     
  [5] "tBodyAcc-std()-X_4"                       "tBodyAcc-std()-Y_5"                      
  [7] "tBodyAcc-std()-Z_6"                       "tBodyAcc-mad()-X_7"                      
  [9] "tBodyAcc-mad()-Y_8"                       "tBodyAcc-mad()-Z_9"                      
 [11] "tBodyAcc-max()-X_10"                      "tBodyAcc-max()-Y_11"                     
 [13] "tBodyAcc-max()-Z_12"                      "tBodyAcc-min()-X_13"                     
 [15] "tBodyAcc-min()-Y_14"                      "tBodyAcc-min()-Z_15"                     
 [17] "tBodyAcc-sma()_16"                        "tBodyAcc-energy()-X_17"                  
 [19] "tBodyAcc-energy()-Y_18"                   "tBodyAcc-energy()-Z_19"                  
 [21] "tBodyAcc-iqr()-X_20"                      "tBodyAcc-iqr()-Y_21"                     
 [23] "tBodyAcc-iqr()-Z_22"                      "tBodyAcc-entropy()-X_23"                 
 [25] "tBodyAcc-entropy()-Y_24"                  "tBodyAcc-entropy()-Z_25"                 
 [27] "tBodyAcc-arCoeff()-X,1_26"                "tBodyAcc-arCoeff()-X,2_27"               
 [29] "tBodyAcc-arCoeff()-X,3_28"                "tBodyAcc-arCoeff()-X,4_29"               
 [31] "tBodyAcc-arCoeff()-Y,1_30"                "tBodyAcc-arCoeff()-Y,2_31"               
 [33] "tBodyAcc-arCoeff()-Y,3_32"                "tBodyAcc-arCoeff()-Y,4_33"               
 [35] "tBodyAcc-arCoeff()-Z,1_34"                "tBodyAcc-arCoeff()-Z,2_35"               
 [37] "tBodyAcc-arCoeff()-Z,3_36"                "tBodyAcc-arCoeff()-Z,4_37"               
 [39] "tBodyAcc-correlation()-X,Y_38"            "tBodyAcc-correlation()-X,Z_39"           
 [41] "tBodyAcc-correlation()-Y,Z_40"            "tGravityAcc-mean()-X_41"                 
 [43] "tGravityAcc-mean()-Y_42"                  "tGravityAcc-mean()-Z_43"                 
 [45] "tGravityAcc-std()-X_44"                   "tGravityAcc-std()-Y_45"                  
 [47] "tGravityAcc-std()-Z_46"                   "tGravityAcc-mad()-X_47"                  
 [49] "tGravityAcc-mad()-Y_48"                   "tGravityAcc-mad()-Z_49"                  
 [51] "tGravityAcc-max()-X_50"                   "tGravityAcc-max()-Y_51"                  
 [53] "tGravityAcc-max()-Z_52"                   "tGravityAcc-min()-X_53"                  
 [55] "tGravityAcc-min()-Y_54"                   "tGravityAcc-min()-Z_55"                  
 [57] "tGravityAcc-sma()_56"                     "tGravityAcc-energy()-X_57"               
 [59] "tGravityAcc-energy()-Y_58"                "tGravityAcc-energy()-Z_59"               
 [61] "tGravityAcc-iqr()-X_60"                   "tGravityAcc-iqr()-Y_61"                  
 [63] "tGravityAcc-iqr()-Z_62"                   "tGravityAcc-entropy()-X_63"              
 [65] "tGravityAcc-entropy()-Y_64"               "tGravityAcc-entropy()-Z_65"              
 [67] "tGravityAcc-arCoeff()-X,1_66"             "tGravityAcc-arCoeff()-X,2_67"            
 [69] "tGravityAcc-arCoeff()-X,3_68"             "tGravityAcc-arCoeff()-X,4_69"            
 [71] "tGravityAcc-arCoeff()-Y,1_70"             "tGravityAcc-arCoeff()-Y,2_71"            
 [73] "tGravityAcc-arCoeff()-Y,3_72"             "tGravityAcc-arCoeff()-Y,4_73"            
 [75] "tGravityAcc-arCoeff()-Z,1_74"             "tGravityAcc-arCoeff()-Z,2_75"            
 [77] "tGravityAcc-arCoeff()-Z,3_76"             "tGravityAcc-arCoeff()-Z,4_77"            
 [79] "tGravityAcc-correlation()-X,Y_78"         "tGravityAcc-correlation()-X,Z_79"        
 [81] "tGravityAcc-correlation()-Y,Z_80"         "tBodyAccJerk-mean()-X_81"                
 [83] "tBodyAccJerk-mean()-Y_82"                 "tBodyAccJerk-mean()-Z_83"                
 [85] "tBodyAccJerk-std()-X_84"                  "tBodyAccJerk-std()-Y_85"                 
 [87] "tBodyAccJerk-std()-Z_86"                  "tBodyAccJerk-mad()-X_87"                 
 [89] "tBodyAccJerk-mad()-Y_88"                  "tBodyAccJerk-mad()-Z_89"                 
 [91] "tBodyAccJerk-max()-X_90"                  "tBodyAccJerk-max()-Y_91"                 
 [93] "tBodyAccJerk-max()-Z_92"                  "tBodyAccJerk-min()-X_93"                 
 [95] "tBodyAccJerk-min()-Y_94"                  "tBodyAccJerk-min()-Z_95"                 
 [97] "tBodyAccJerk-sma()_96"                    "tBodyAccJerk-energy()-X_97"              
 [99] "tBodyAccJerk-energy()-Y_98"               "tBodyAccJerk-energy()-Z_99"              
[101] "tBodyAccJerk-iqr()-X_100"                 "tBodyAccJerk-iqr()-Y_101"                
[103] "tBodyAccJerk-iqr()-Z_102"                 "tBodyAccJerk-entropy()-X_103"            
[105] "tBodyAccJerk-entropy()-Y_104"             "tBodyAccJerk-entropy()-Z_105"            
[107] "tBodyAccJerk-arCoeff()-X,1_106"           "tBodyAccJerk-arCoeff()-X,2_107"          
[109] "tBodyAccJerk-arCoeff()-X,3_108"           "tBodyAccJerk-arCoeff()-X,4_109"          
[111] "tBodyAccJerk-arCoeff()-Y,1_110"           "tBodyAccJerk-arCoeff()-Y,2_111"          
[113] "tBodyAccJerk-arCoeff()-Y,3_112"           "tBodyAccJerk-arCoeff()-Y,4_113"          
[115] "tBodyAccJerk-arCoeff()-Z,1_114"           "tBodyAccJerk-arCoeff()-Z,2_115"          
[117] "tBodyAccJerk-arCoeff()-Z,3_116"           "tBodyAccJerk-arCoeff()-Z,4_117"          
[119] "tBodyAccJerk-correlation()-X,Y_118"       "tBodyAccJerk-correlation()-X,Z_119"      
[121] "tBodyAccJerk-correlation()-Y,Z_120"       "tBodyGyro-mean()-X_121"                  
[123] "tBodyGyro-mean()-Y_122"                   "tBodyGyro-mean()-Z_123"                  
[125] "tBodyGyro-std()-X_124"                    "tBodyGyro-std()-Y_125"                   
[127] "tBodyGyro-std()-Z_126"                    "tBodyGyro-mad()-X_127"                   
[129] "tBodyGyro-mad()-Y_128"                    "tBodyGyro-mad()-Z_129"                   
[131] "tBodyGyro-max()-X_130"                    "tBodyGyro-max()-Y_131"                   
[133] "tBodyGyro-max()-Z_132"                    "tBodyGyro-min()-X_133"                   
[135] "tBodyGyro-min()-Y_134"                    "tBodyGyro-min()-Z_135"                   
[137] "tBodyGyro-sma()_136"                      "tBodyGyro-energy()-X_137"                
[139] "tBodyGyro-energy()-Y_138"                 "tBodyGyro-energy()-Z_139"                
[141] "tBodyGyro-iqr()-X_140"                    "tBodyGyro-iqr()-Y_141"                   
[143] "tBodyGyro-iqr()-Z_142"                    "tBodyGyro-entropy()-X_143"               
[145] "tBodyGyro-entropy()-Y_144"                "tBodyGyro-entropy()-Z_145"               
[147] "tBodyGyro-arCoeff()-X,1_146"              "tBodyGyro-arCoeff()-X,2_147"             
[149] "tBodyGyro-arCoeff()-X,3_148"              "tBodyGyro-arCoeff()-X,4_149"             
[151] "tBodyGyro-arCoeff()-Y,1_150"              "tBodyGyro-arCoeff()-Y,2_151"             
[153] "tBodyGyro-arCoeff()-Y,3_152"              "tBodyGyro-arCoeff()-Y,4_153"             
[155] "tBodyGyro-arCoeff()-Z,1_154"              "tBodyGyro-arCoeff()-Z,2_155"             
[157] "tBodyGyro-arCoeff()-Z,3_156"              "tBodyGyro-arCoeff()-Z,4_157"             
[159] "tBodyGyro-correlation()-X,Y_158"          "tBodyGyro-correlation()-X,Z_159"         
[161] "tBodyGyro-correlation()-Y,Z_160"          "tBodyGyroJerk-mean()-X_161"              
[163] "tBodyGyroJerk-mean()-Y_162"               "tBodyGyroJerk-mean()-Z_163"              
[165] "tBodyGyroJerk-std()-X_164"                "tBodyGyroJerk-std()-Y_165"               
[167] "tBodyGyroJerk-std()-Z_166"                "tBodyGyroJerk-mad()-X_167"               
[169] "tBodyGyroJerk-mad()-Y_168"                "tBodyGyroJerk-mad()-Z_169"               
[171] "tBodyGyroJerk-max()-X_170"                "tBodyGyroJerk-max()-Y_171"               
[173] "tBodyGyroJerk-max()-Z_172"                "tBodyGyroJerk-min()-X_173"               
[175] "tBodyGyroJerk-min()-Y_174"                "tBodyGyroJerk-min()-Z_175"               
[177] "tBodyGyroJerk-sma()_176"                  "tBodyGyroJerk-energy()-X_177"            
[179] "tBodyGyroJerk-energy()-Y_178"             "tBodyGyroJerk-energy()-Z_179"            
[181] "tBodyGyroJerk-iqr()-X_180"                "tBodyGyroJerk-iqr()-Y_181"               
[183] "tBodyGyroJerk-iqr()-Z_182"                "tBodyGyroJerk-entropy()-X_183"           
[185] "tBodyGyroJerk-entropy()-Y_184"            "tBodyGyroJerk-entropy()-Z_185"           
[187] "tBodyGyroJerk-arCoeff()-X,1_186"          "tBodyGyroJerk-arCoeff()-X,2_187"         
[189] "tBodyGyroJerk-arCoeff()-X,3_188"          "tBodyGyroJerk-arCoeff()-X,4_189"         
[191] "tBodyGyroJerk-arCoeff()-Y,1_190"          "tBodyGyroJerk-arCoeff()-Y,2_191"         
[193] "tBodyGyroJerk-arCoeff()-Y,3_192"          "tBodyGyroJerk-arCoeff()-Y,4_193"         
[195] "tBodyGyroJerk-arCoeff()-Z,1_194"          "tBodyGyroJerk-arCoeff()-Z,2_195"         
[197] "tBodyGyroJerk-arCoeff()-Z,3_196"          "tBodyGyroJerk-arCoeff()-Z,4_197"         
[199] "tBodyGyroJerk-correlation()-X,Y_198"      "tBodyGyroJerk-correlation()-X,Z_199"     
[201] "tBodyGyroJerk-correlation()-Y,Z_200"      "tBodyAccMag-mean()_201"                  
[203] "tBodyAccMag-std()_202"                    "tBodyAccMag-mad()_203"                   
[205] "tBodyAccMag-max()_204"                    "tBodyAccMag-min()_205"                   
[207] "tBodyAccMag-sma()_206"                    "tBodyAccMag-energy()_207"                
[209] "tBodyAccMag-iqr()_208"                    "tBodyAccMag-entropy()_209"               
[211] "tBodyAccMag-arCoeff()1_210"               "tBodyAccMag-arCoeff()2_211"              
[213] "tBodyAccMag-arCoeff()3_212"               "tBodyAccMag-arCoeff()4_213"              
[215] "tGravityAccMag-mean()_214"                "tGravityAccMag-std()_215"                
[217] "tGravityAccMag-mad()_216"                 "tGravityAccMag-max()_217"                
[219] "tGravityAccMag-min()_218"                 "tGravityAccMag-sma()_219"                
[221] "tGravityAccMag-energy()_220"              "tGravityAccMag-iqr()_221"                
[223] "tGravityAccMag-entropy()_222"             "tGravityAccMag-arCoeff()1_223"           
[225] "tGravityAccMag-arCoeff()2_224"            "tGravityAccMag-arCoeff()3_225"           
[227] "tGravityAccMag-arCoeff()4_226"            "tBodyAccJerkMag-mean()_227"              
[229] "tBodyAccJerkMag-std()_228"                "tBodyAccJerkMag-mad()_229"               
[231] "tBodyAccJerkMag-max()_230"                "tBodyAccJerkMag-min()_231"               
[233] "tBodyAccJerkMag-sma()_232"                "tBodyAccJerkMag-energy()_233"            
[235] "tBodyAccJerkMag-iqr()_234"                "tBodyAccJerkMag-entropy()_235"           
[237] "tBodyAccJerkMag-arCoeff()1_236"           "tBodyAccJerkMag-arCoeff()2_237"          
[239] "tBodyAccJerkMag-arCoeff()3_238"           "tBodyAccJerkMag-arCoeff()4_239"          
[241] "tBodyGyroMag-mean()_240"                  "tBodyGyroMag-std()_241"                  
[243] "tBodyGyroMag-mad()_242"                   "tBodyGyroMag-max()_243"                  
[245] "tBodyGyroMag-min()_244"                   "tBodyGyroMag-sma()_245"                  
[247] "tBodyGyroMag-energy()_246"                "tBodyGyroMag-iqr()_247"                  
[249] "tBodyGyroMag-entropy()_248"               "tBodyGyroMag-arCoeff()1_249"             
[251] "tBodyGyroMag-arCoeff()2_250"              "tBodyGyroMag-arCoeff()3_251"             
[253] "tBodyGyroMag-arCoeff()4_252"              "tBodyGyroJerkMag-mean()_253"             
[255] "tBodyGyroJerkMag-std()_254"               "tBodyGyroJerkMag-mad()_255"              
[257] "tBodyGyroJerkMag-max()_256"               "tBodyGyroJerkMag-min()_257"              
[259] "tBodyGyroJerkMag-sma()_258"               "tBodyGyroJerkMag-energy()_259"           
[261] "tBodyGyroJerkMag-iqr()_260"               "tBodyGyroJerkMag-entropy()_261"          
[263] "tBodyGyroJerkMag-arCoeff()1_262"          "tBodyGyroJerkMag-arCoeff()2_263"         
[265] "tBodyGyroJerkMag-arCoeff()3_264"          "tBodyGyroJerkMag-arCoeff()4_265"         
[267] "fBodyAcc-mean()-X_266"                    "fBodyAcc-mean()-Y_267"                   
[269] "fBodyAcc-mean()-Z_268"                    "fBodyAcc-std()-X_269"                    
[271] "fBodyAcc-std()-Y_270"                     "fBodyAcc-std()-Z_271"                    
[273] "fBodyAcc-mad()-X_272"                     "fBodyAcc-mad()-Y_273"                    
[275] "fBodyAcc-mad()-Z_274"                     "fBodyAcc-max()-X_275"                    
[277] "fBodyAcc-max()-Y_276"                     "fBodyAcc-max()-Z_277"                    
[279] "fBodyAcc-min()-X_278"                     "fBodyAcc-min()-Y_279"                    
[281] "fBodyAcc-min()-Z_280"                     "fBodyAcc-sma()_281"                      
[283] "fBodyAcc-energy()-X_282"                  "fBodyAcc-energy()-Y_283"                 
[285] "fBodyAcc-energy()-Z_284"                  "fBodyAcc-iqr()-X_285"                    
[287] "fBodyAcc-iqr()-Y_286"                     "fBodyAcc-iqr()-Z_287"                    
[289] "fBodyAcc-entropy()-X_288"                 "fBodyAcc-entropy()-Y_289"                
[291] "fBodyAcc-entropy()-Z_290"                 "fBodyAcc-maxInds-X_291"                  
[293] "fBodyAcc-maxInds-Y_292"                   "fBodyAcc-maxInds-Z_293"                  
[295] "fBodyAcc-meanFreq()-X_294"                "fBodyAcc-meanFreq()-Y_295"               
[297] "fBodyAcc-meanFreq()-Z_296"                "fBodyAcc-skewness()-X_297"               
[299] "fBodyAcc-kurtosis()-X_298"                "fBodyAcc-skewness()-Y_299"               
[301] "fBodyAcc-kurtosis()-Y_300"                "fBodyAcc-skewness()-Z_301"               
[303] "fBodyAcc-kurtosis()-Z_302"                "fBodyAcc-bandsEnergy()-1,8_303"          
[305] "fBodyAcc-bandsEnergy()-9,16_304"          "fBodyAcc-bandsEnergy()-17,24_305"        
[307] "fBodyAcc-bandsEnergy()-25,32_306"         "fBodyAcc-bandsEnergy()-33,40_307"        
[309] "fBodyAcc-bandsEnergy()-41,48_308"         "fBodyAcc-bandsEnergy()-49,56_309"        
[311] "fBodyAcc-bandsEnergy()-57,64_310"         "fBodyAcc-bandsEnergy()-1,16_311"         
[313] "fBodyAcc-bandsEnergy()-17,32_312"         "fBodyAcc-bandsEnergy()-33,48_313"        
[315] "fBodyAcc-bandsEnergy()-49,64_314"         "fBodyAcc-bandsEnergy()-1,24_315"         
[317] "fBodyAcc-bandsEnergy()-25,48_316"         "fBodyAcc-bandsEnergy()-1,8_317"          
[319] "fBodyAcc-bandsEnergy()-9,16_318"          "fBodyAcc-bandsEnergy()-17,24_319"        
[321] "fBodyAcc-bandsEnergy()-25,32_320"         "fBodyAcc-bandsEnergy()-33,40_321"        
[323] "fBodyAcc-bandsEnergy()-41,48_322"         "fBodyAcc-bandsEnergy()-49,56_323"        
[325] "fBodyAcc-bandsEnergy()-57,64_324"         "fBodyAcc-bandsEnergy()-1,16_325"         
[327] "fBodyAcc-bandsEnergy()-17,32_326"         "fBodyAcc-bandsEnergy()-33,48_327"        
[329] "fBodyAcc-bandsEnergy()-49,64_328"         "fBodyAcc-bandsEnergy()-1,24_329"         
[331] "fBodyAcc-bandsEnergy()-25,48_330"         "fBodyAcc-bandsEnergy()-1,8_331"          
[333] "fBodyAcc-bandsEnergy()-9,16_332"          "fBodyAcc-bandsEnergy()-17,24_333"        
[335] "fBodyAcc-bandsEnergy()-25,32_334"         "fBodyAcc-bandsEnergy()-33,40_335"        
[337] "fBodyAcc-bandsEnergy()-41,48_336"         "fBodyAcc-bandsEnergy()-49,56_337"        
[339] "fBodyAcc-bandsEnergy()-57,64_338"         "fBodyAcc-bandsEnergy()-1,16_339"         
[341] "fBodyAcc-bandsEnergy()-17,32_340"         "fBodyAcc-bandsEnergy()-33,48_341"        
[343] "fBodyAcc-bandsEnergy()-49,64_342"         "fBodyAcc-bandsEnergy()-1,24_343"         
[345] "fBodyAcc-bandsEnergy()-25,48_344"         "fBodyAccJerk-mean()-X_345"               
[347] "fBodyAccJerk-mean()-Y_346"                "fBodyAccJerk-mean()-Z_347"               
[349] "fBodyAccJerk-std()-X_348"                 "fBodyAccJerk-std()-Y_349"                
[351] "fBodyAccJerk-std()-Z_350"                 "fBodyAccJerk-mad()-X_351"                
[353] "fBodyAccJerk-mad()-Y_352"                 "fBodyAccJerk-mad()-Z_353"                
[355] "fBodyAccJerk-max()-X_354"                 "fBodyAccJerk-max()-Y_355"                
[357] "fBodyAccJerk-max()-Z_356"                 "fBodyAccJerk-min()-X_357"                
[359] "fBodyAccJerk-min()-Y_358"                 "fBodyAccJerk-min()-Z_359"                
[361] "fBodyAccJerk-sma()_360"                   "fBodyAccJerk-energy()-X_361"             
[363] "fBodyAccJerk-energy()-Y_362"              "fBodyAccJerk-energy()-Z_363"             
[365] "fBodyAccJerk-iqr()-X_364"                 "fBodyAccJerk-iqr()-Y_365"                
[367] "fBodyAccJerk-iqr()-Z_366"                 "fBodyAccJerk-entropy()-X_367"            
[369] "fBodyAccJerk-entropy()-Y_368"             "fBodyAccJerk-entropy()-Z_369"            
[371] "fBodyAccJerk-maxInds-X_370"               "fBodyAccJerk-maxInds-Y_371"              
[373] "fBodyAccJerk-maxInds-Z_372"               "fBodyAccJerk-meanFreq()-X_373"           
[375] "fBodyAccJerk-meanFreq()-Y_374"            "fBodyAccJerk-meanFreq()-Z_375"           
[377] "fBodyAccJerk-skewness()-X_376"            "fBodyAccJerk-kurtosis()-X_377"           
[379] "fBodyAccJerk-skewness()-Y_378"            "fBodyAccJerk-kurtosis()-Y_379"           
[381] "fBodyAccJerk-skewness()-Z_380"            "fBodyAccJerk-kurtosis()-Z_381"           
[383] "fBodyAccJerk-bandsEnergy()-1,8_382"       "fBodyAccJerk-bandsEnergy()-9,16_383"     
[385] "fBodyAccJerk-bandsEnergy()-17,24_384"     "fBodyAccJerk-bandsEnergy()-25,32_385"    
[387] "fBodyAccJerk-bandsEnergy()-33,40_386"     "fBodyAccJerk-bandsEnergy()-41,48_387"    
[389] "fBodyAccJerk-bandsEnergy()-49,56_388"     "fBodyAccJerk-bandsEnergy()-57,64_389"    
[391] "fBodyAccJerk-bandsEnergy()-1,16_390"      "fBodyAccJerk-bandsEnergy()-17,32_391"    
[393] "fBodyAccJerk-bandsEnergy()-33,48_392"     "fBodyAccJerk-bandsEnergy()-49,64_393"    
[395] "fBodyAccJerk-bandsEnergy()-1,24_394"      "fBodyAccJerk-bandsEnergy()-25,48_395"    
[397] "fBodyAccJerk-bandsEnergy()-1,8_396"       "fBodyAccJerk-bandsEnergy()-9,16_397"     
[399] "fBodyAccJerk-bandsEnergy()-17,24_398"     "fBodyAccJerk-bandsEnergy()-25,32_399"    
[401] "fBodyAccJerk-bandsEnergy()-33,40_400"     "fBodyAccJerk-bandsEnergy()-41,48_401"    
[403] "fBodyAccJerk-bandsEnergy()-49,56_402"     "fBodyAccJerk-bandsEnergy()-57,64_403"    
[405] "fBodyAccJerk-bandsEnergy()-1,16_404"      "fBodyAccJerk-bandsEnergy()-17,32_405"    
[407] "fBodyAccJerk-bandsEnergy()-33,48_406"     "fBodyAccJerk-bandsEnergy()-49,64_407"    
[409] "fBodyAccJerk-bandsEnergy()-1,24_408"      "fBodyAccJerk-bandsEnergy()-25,48_409"    
[411] "fBodyAccJerk-bandsEnergy()-1,8_410"       "fBodyAccJerk-bandsEnergy()-9,16_411"     
[413] "fBodyAccJerk-bandsEnergy()-17,24_412"     "fBodyAccJerk-bandsEnergy()-25,32_413"    
[415] "fBodyAccJerk-bandsEnergy()-33,40_414"     "fBodyAccJerk-bandsEnergy()-41,48_415"    
[417] "fBodyAccJerk-bandsEnergy()-49,56_416"     "fBodyAccJerk-bandsEnergy()-57,64_417"    
[419] "fBodyAccJerk-bandsEnergy()-1,16_418"      "fBodyAccJerk-bandsEnergy()-17,32_419"    
[421] "fBodyAccJerk-bandsEnergy()-33,48_420"     "fBodyAccJerk-bandsEnergy()-49,64_421"    
[423] "fBodyAccJerk-bandsEnergy()-1,24_422"      "fBodyAccJerk-bandsEnergy()-25,48_423"    
[425] "fBodyGyro-mean()-X_424"                   "fBodyGyro-mean()-Y_425"                  
[427] "fBodyGyro-mean()-Z_426"                   "fBodyGyro-std()-X_427"                   
[429] "fBodyGyro-std()-Y_428"                    "fBodyGyro-std()-Z_429"                   
[431] "fBodyGyro-mad()-X_430"                    "fBodyGyro-mad()-Y_431"                   
[433] "fBodyGyro-mad()-Z_432"                    "fBodyGyro-max()-X_433"                   
[435] "fBodyGyro-max()-Y_434"                    "fBodyGyro-max()-Z_435"                   
[437] "fBodyGyro-min()-X_436"                    "fBodyGyro-min()-Y_437"                   
[439] "fBodyGyro-min()-Z_438"                    "fBodyGyro-sma()_439"                     
[441] "fBodyGyro-energy()-X_440"                 "fBodyGyro-energy()-Y_441"                
[443] "fBodyGyro-energy()-Z_442"                 "fBodyGyro-iqr()-X_443"                   
[445] "fBodyGyro-iqr()-Y_444"                    "fBodyGyro-iqr()-Z_445"                   
[447] "fBodyGyro-entropy()-X_446"                "fBodyGyro-entropy()-Y_447"               
[449] "fBodyGyro-entropy()-Z_448"                "fBodyGyro-maxInds-X_449"                 
[451] "fBodyGyro-maxInds-Y_450"                  "fBodyGyro-maxInds-Z_451"                 
[453] "fBodyGyro-meanFreq()-X_452"               "fBodyGyro-meanFreq()-Y_453"              
[455] "fBodyGyro-meanFreq()-Z_454"               "fBodyGyro-skewness()-X_455"              
[457] "fBodyGyro-kurtosis()-X_456"               "fBodyGyro-skewness()-Y_457"              
[459] "fBodyGyro-kurtosis()-Y_458"               "fBodyGyro-skewness()-Z_459"              
[461] "fBodyGyro-kurtosis()-Z_460"               "fBodyGyro-bandsEnergy()-1,8_461"         
[463] "fBodyGyro-bandsEnergy()-9,16_462"         "fBodyGyro-bandsEnergy()-17,24_463"       
[465] "fBodyGyro-bandsEnergy()-25,32_464"        "fBodyGyro-bandsEnergy()-33,40_465"       
[467] "fBodyGyro-bandsEnergy()-41,48_466"        "fBodyGyro-bandsEnergy()-49,56_467"       
[469] "fBodyGyro-bandsEnergy()-57,64_468"        "fBodyGyro-bandsEnergy()-1,16_469"        
[471] "fBodyGyro-bandsEnergy()-17,32_470"        "fBodyGyro-bandsEnergy()-33,48_471"       
[473] "fBodyGyro-bandsEnergy()-49,64_472"        "fBodyGyro-bandsEnergy()-1,24_473"        
[475] "fBodyGyro-bandsEnergy()-25,48_474"        "fBodyGyro-bandsEnergy()-1,8_475"         
[477] "fBodyGyro-bandsEnergy()-9,16_476"         "fBodyGyro-bandsEnergy()-17,24_477"       
[479] "fBodyGyro-bandsEnergy()-25,32_478"        "fBodyGyro-bandsEnergy()-33,40_479"       
[481] "fBodyGyro-bandsEnergy()-41,48_480"        "fBodyGyro-bandsEnergy()-49,56_481"       
[483] "fBodyGyro-bandsEnergy()-57,64_482"        "fBodyGyro-bandsEnergy()-1,16_483"        
[485] "fBodyGyro-bandsEnergy()-17,32_484"        "fBodyGyro-bandsEnergy()-33,48_485"       
[487] "fBodyGyro-bandsEnergy()-49,64_486"        "fBodyGyro-bandsEnergy()-1,24_487"        
[489] "fBodyGyro-bandsEnergy()-25,48_488"        "fBodyGyro-bandsEnergy()-1,8_489"         
[491] "fBodyGyro-bandsEnergy()-9,16_490"         "fBodyGyro-bandsEnergy()-17,24_491"       
[493] "fBodyGyro-bandsEnergy()-25,32_492"        "fBodyGyro-bandsEnergy()-33,40_493"       
[495] "fBodyGyro-bandsEnergy()-41,48_494"        "fBodyGyro-bandsEnergy()-49,56_495"       
[497] "fBodyGyro-bandsEnergy()-57,64_496"        "fBodyGyro-bandsEnergy()-1,16_497"        
[499] "fBodyGyro-bandsEnergy()-17,32_498"        "fBodyGyro-bandsEnergy()-33,48_499"       
[501] "fBodyGyro-bandsEnergy()-49,64_500"        "fBodyGyro-bandsEnergy()-1,24_501"        
[503] "fBodyGyro-bandsEnergy()-25,48_502"        "fBodyAccMag-mean()_503"                  
[505] "fBodyAccMag-std()_504"                    "fBodyAccMag-mad()_505"                   
[507] "fBodyAccMag-max()_506"                    "fBodyAccMag-min()_507"                   
[509] "fBodyAccMag-sma()_508"                    "fBodyAccMag-energy()_509"                
[511] "fBodyAccMag-iqr()_510"                    "fBodyAccMag-entropy()_511"               
[513] "fBodyAccMag-maxInds_512"                  "fBodyAccMag-meanFreq()_513"              
[515] "fBodyAccMag-skewness()_514"               "fBodyAccMag-kurtosis()_515"              
[517] "fBodyBodyAccJerkMag-mean()_516"           "fBodyBodyAccJerkMag-std()_517"           
[519] "fBodyBodyAccJerkMag-mad()_518"            "fBodyBodyAccJerkMag-max()_519"           
[521] "fBodyBodyAccJerkMag-min()_520"            "fBodyBodyAccJerkMag-sma()_521"           
[523] "fBodyBodyAccJerkMag-energy()_522"         "fBodyBodyAccJerkMag-iqr()_523"           
[525] "fBodyBodyAccJerkMag-entropy()_524"        "fBodyBodyAccJerkMag-maxInds_525"         
[527] "fBodyBodyAccJerkMag-meanFreq()_526"       "fBodyBodyAccJerkMag-skewness()_527"      
[529] "fBodyBodyAccJerkMag-kurtosis()_528"       "fBodyBodyGyroMag-mean()_529"             
[531] "fBodyBodyGyroMag-std()_530"               "fBodyBodyGyroMag-mad()_531"              
[533] "fBodyBodyGyroMag-max()_532"               "fBodyBodyGyroMag-min()_533"              
[535] "fBodyBodyGyroMag-sma()_534"               "fBodyBodyGyroMag-energy()_535"           
[537] "fBodyBodyGyroMag-iqr()_536"               "fBodyBodyGyroMag-entropy()_537"          
[539] "fBodyBodyGyroMag-maxInds_538"             "fBodyBodyGyroMag-meanFreq()_539"         
[541] "fBodyBodyGyroMag-skewness()_540"          "fBodyBodyGyroMag-kurtosis()_541"         
[543] "fBodyBodyGyroJerkMag-mean()_542"          "fBodyBodyGyroJerkMag-std()_543"          
[545] "fBodyBodyGyroJerkMag-mad()_544"           "fBodyBodyGyroJerkMag-max()_545"          
[547] "fBodyBodyGyroJerkMag-min()_546"           "fBodyBodyGyroJerkMag-sma()_547"          
[549] "fBodyBodyGyroJerkMag-energy()_548"        "fBodyBodyGyroJerkMag-iqr()_549"          
[551] "fBodyBodyGyroJerkMag-entropy()_550"       "fBodyBodyGyroJerkMag-maxInds_551"        
[553] "fBodyBodyGyroJerkMag-meanFreq()_552"      "fBodyBodyGyroJerkMag-skewness()_553"     
[555] "fBodyBodyGyroJerkMag-kurtosis()_554"      "angle(tBodyAccMean,gravity)_555"         
[557] "angle(tBodyAccJerkMean),gravityMean)_556" "angle(tBodyGyroMean,gravityMean)_557"    
[559] "angle(tBodyGyroJerkMean,gravityMean)_558" "angle(X,gravityMean)_559"                
[561] "angle(Y,gravityMean)_560"                 "angle(Z,gravityMean)_561"                
[563] "activity"                                 "subject"                                 

2. Extracts only the measurements on the mean and standard deviation for each measurement.
   * tidy_data is created by subsetting only the following columns from the Merged Data table: datasource, subject, activity, contains("mean"), contains("std")
   * This new table contains 89 features and 10299 observations.
   
   * The column names at this point:
   
 [1] "datasource"                               "subject"                                 
 [3] "activity"                                 "tBodyAcc-mean()-X_1"                     
 [5] "tBodyAcc-mean()-Y_2"                      "tBodyAcc-mean()-Z_3"                     
 [7] "tGravityAcc-mean()-X_41"                  "tGravityAcc-mean()-Y_42"                 
 [9] "tGravityAcc-mean()-Z_43"                  "tBodyAccJerk-mean()-X_81"                
[11] "tBodyAccJerk-mean()-Y_82"                 "tBodyAccJerk-mean()-Z_83"                
[13] "tBodyGyro-mean()-X_121"                   "tBodyGyro-mean()-Y_122"                  
[15] "tBodyGyro-mean()-Z_123"                   "tBodyGyroJerk-mean()-X_161"              
[17] "tBodyGyroJerk-mean()-Y_162"               "tBodyGyroJerk-mean()-Z_163"              
[19] "tBodyAccMag-mean()_201"                   "tGravityAccMag-mean()_214"               
[21] "tBodyAccJerkMag-mean()_227"               "tBodyGyroMag-mean()_240"                 
[23] "tBodyGyroJerkMag-mean()_253"              "fBodyAcc-mean()-X_266"                   
[25] "fBodyAcc-mean()-Y_267"                    "fBodyAcc-mean()-Z_268"                   
[27] "fBodyAcc-meanFreq()-X_294"                "fBodyAcc-meanFreq()-Y_295"               
[29] "fBodyAcc-meanFreq()-Z_296"                "fBodyAccJerk-mean()-X_345"               
[31] "fBodyAccJerk-mean()-Y_346"                "fBodyAccJerk-mean()-Z_347"               
[33] "fBodyAccJerk-meanFreq()-X_373"            "fBodyAccJerk-meanFreq()-Y_374"           
[35] "fBodyAccJerk-meanFreq()-Z_375"            "fBodyGyro-mean()-X_424"                  
[37] "fBodyGyro-mean()-Y_425"                   "fBodyGyro-mean()-Z_426"                  
[39] "fBodyGyro-meanFreq()-X_452"               "fBodyGyro-meanFreq()-Y_453"              
[41] "fBodyGyro-meanFreq()-Z_454"               "fBodyAccMag-mean()_503"                  
[43] "fBodyAccMag-meanFreq()_513"               "fBodyBodyAccJerkMag-mean()_516"          
[45] "fBodyBodyAccJerkMag-meanFreq()_526"       "fBodyBodyGyroMag-mean()_529"             
[47] "fBodyBodyGyroMag-meanFreq()_539"          "fBodyBodyGyroJerkMag-mean()_542"         
[49] "fBodyBodyGyroJerkMag-meanFreq()_552"      "angle(tBodyAccMean,gravity)_555"         
[51] "angle(tBodyAccJerkMean),gravityMean)_556" "angle(tBodyGyroMean,gravityMean)_557"    
[53] "angle(tBodyGyroJerkMean,gravityMean)_558" "angle(X,gravityMean)_559"                
[55] "angle(Y,gravityMean)_560"                 "angle(Z,gravityMean)_561"                
[57] "tBodyAcc-std()-X_4"                       "tBodyAcc-std()-Y_5"                      
[59] "tBodyAcc-std()-Z_6"                       "tGravityAcc-std()-X_44"                  
[61] "tGravityAcc-std()-Y_45"                   "tGravityAcc-std()-Z_46"                  
[63] "tBodyAccJerk-std()-X_84"                  "tBodyAccJerk-std()-Y_85"                 
[65] "tBodyAccJerk-std()-Z_86"                  "tBodyGyro-std()-X_124"                   
[67] "tBodyGyro-std()-Y_125"                    "tBodyGyro-std()-Z_126"                   
[69] "tBodyGyroJerk-std()-X_164"                "tBodyGyroJerk-std()-Y_165"               
[71] "tBodyGyroJerk-std()-Z_166"                "tBodyAccMag-std()_202"                   
[73] "tGravityAccMag-std()_215"                 "tBodyAccJerkMag-std()_228"               
[75] "tBodyGyroMag-std()_241"                   "tBodyGyroJerkMag-std()_254"              
[77] "fBodyAcc-std()-X_269"                     "fBodyAcc-std()-Y_270"                    
[79] "fBodyAcc-std()-Z_271"                     "fBodyAccJerk-std()-X_348"                
[81] "fBodyAccJerk-std()-Y_349"                 "fBodyAccJerk-std()-Z_350"                
[83] "fBodyGyro-std()-X_427"                    "fBodyGyro-std()-Y_428"                   
[85] "fBodyGyro-std()-Z_429"                    "fBodyAccMag-std()_504"                   
[87] "fBodyBodyAccJerkMag-std()_517"            "fBodyBodyGyroMag-std()_530"              
[89] "fBodyBodyGyroJerkMag-std()_543"          


3. Uses descriptive activity names to name the activities in the data set
   * Update the Activity field to be character type, to be able to hold the descriptive name. Originally numeric, which can't hold string data.
   * Update the Activity field to be descriptive names, looking up the names in the activityLabels table.
   
   
4. Appropriately labels the data set with descriptive variable names.
   * Make all column names lowercase.
   * Get rid of the field index number which was added towards the top of this script to help differentiate the column names.
   * Rename the abbreviations in the field names with their longer equivalents
   * Get rid of parentheses and commas
      
   * The column names at this point:
   
 [1] "datasource"                                            "subject"                                              
 [3] "activity"                                              "timebodyaccelerometer-mean-x"                         
 [5] "timebodyaccelerometer-mean-y"                          "timebodyaccelerometer-mean-z"                         
 [7] "timegravityaccelerometer-mean-x"                       "timegravityaccelerometer-mean-y"                      
 [9] "timegravityaccelerometer-mean-z"                       "timebodyaccelerometerjerk-mean-x"                     
[11] "timebodyaccelerometerjerk-mean-y"                      "timebodyaccelerometerjerk-mean-z"                     
[13] "timebodygyroscope-mean-x"                              "timebodygyroscope-mean-y"                             
[15] "timebodygyroscope-mean-z"                              "timebodygyroscopejerk-mean-x"                         
[17] "timebodygyroscopejerk-mean-y"                          "timebodygyroscopejerk-mean-z"                         
[19] "timebodyaccelerometermagnitude-mean"                   "timegravityaccelerometermagnitude-mean"               
[21] "timebodyaccelerometerjerkmagnitude-mean"               "timebodygyroscopemagnitude-mean"                      
[23] "timebodygyroscopejerkmagnitude-mean"                   "frequencybodyaccelerometer-mean-x"                    
[25] "frequencybodyaccelerometer-mean-y"                     "frequencybodyaccelerometer-mean-z"                    
[27] "frequencybodyaccelerometer-meanfrequency-x"            "frequencybodyaccelerometer-meanfrequency-y"           
[29] "frequencybodyaccelerometer-meanfrequency-z"            "frequencybodyaccelerometerjerk-mean-x"                
[31] "frequencybodyaccelerometerjerk-mean-y"                 "frequencybodyaccelerometerjerk-mean-z"                
[33] "frequencybodyaccelerometerjerk-meanfrequency-x"        "frequencybodyaccelerometerjerk-meanfrequency-y"       
[35] "frequencybodyaccelerometerjerk-meanfrequency-z"        "frequencybodygyroscope-mean-x"                        
[37] "frequencybodygyroscope-mean-y"                         "frequencybodygyroscope-mean-z"                        
[39] "frequencybodygyroscope-meanfrequency-x"                "frequencybodygyroscope-meanfrequency-y"               
[41] "frequencybodygyroscope-meanfrequency-z"                "frequencybodyaccelerometermagnitude-mean"             
[43] "frequencybodyaccelerometermagnitude-meanfrequency"     "frequencybodyaccelerometerjerkmagnitude-mean"         
[45] "frequencybodyaccelerometerjerkmagnitude-meanfrequency" "frequencybodygyroscopemagnitude-mean"                 
[47] "frequencybodygyroscopemagnitude-meanfrequency"         "frequencybodygyroscopejerkmagnitude-mean"             
[49] "frequencybodygyroscopejerkmagnitude-meanfrequency"     "angle-timebodyaccelerometermean-gravity"              
[51] "angle-timebodyaccelerometerjerkmean-gravitymean"       "angle-timebodygyroscopemean-gravitymean"              
[53] "angle-timebodygyroscopejerkmean-gravitymean"           "angle-x-gravitymean"                                  
[55] "angle-y-gravitymean"                                   "angle-z-gravitymean"                                  
[57] "timebodyaccelerometer-std-x"                           "timebodyaccelerometer-std-y"                          
[59] "timebodyaccelerometer-std-z"                           "timegravityaccelerometer-std-x"                       
[61] "timegravityaccelerometer-std-y"                        "timegravityaccelerometer-std-z"                       
[63] "timebodyaccelerometerjerk-std-x"                       "timebodyaccelerometerjerk-std-y"                      
[65] "timebodyaccelerometerjerk-std-z"                       "timebodygyroscope-std-x"                              
[67] "timebodygyroscope-std-y"                               "timebodygyroscope-std-z"                              
[69] "timebodygyroscopejerk-std-x"                           "timebodygyroscopejerk-std-y"                          
[71] "timebodygyroscopejerk-std-z"                           "timebodyaccelerometermagnitude-std"                   
[73] "timegravityaccelerometermagnitude-std"                 "timebodyaccelerometerjerkmagnitude-std"               
[75] "timebodygyroscopemagnitude-std"                        "timebodygyroscopejerkmagnitude-std"                   
[77] "frequencybodyaccelerometer-std-x"                      "frequencybodyaccelerometer-std-y"                     
[79] "frequencybodyaccelerometer-std-z"                      "frequencybodyaccelerometerjerk-std-x"                 
[81] "frequencybodyaccelerometerjerk-std-y"                  "frequencybodyaccelerometerjerk-std-z"                 
[83] "frequencybodygyroscope-std-x"                          "frequencybodygyroscope-std-y"                         
[85] "frequencybodygyroscope-std-z"                          "frequencybodyaccelerometermagnitude-std"              
[87] "frequencybodyaccelerometerjerkmagnitude-std"           "frequencybodygyroscopemagnitude-std"                  
[89] "frequencybodygyroscopejerkmagnitude-std"              

5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
   * Drop the 'datasource' column, since it's not needed in the final output
   * Aggregate the data into a new, final table.
   * Reorder the subject & activity columns
   * Define the final table filename
   * Define the full path for the zip file.
   * Save the file.
   
   * The column names at this point:
   
 [1] "activity"                                              "subject"                                              
 [3] "timebodyaccelerometer-mean-x"                          "timebodyaccelerometer-mean-y"                         
 [5] "timebodyaccelerometer-mean-z"                          "timegravityaccelerometer-mean-x"                      
 [7] "timegravityaccelerometer-mean-y"                       "timegravityaccelerometer-mean-z"                      
 [9] "timebodyaccelerometerjerk-mean-x"                      "timebodyaccelerometerjerk-mean-y"                     
[11] "timebodyaccelerometerjerk-mean-z"                      "timebodygyroscope-mean-x"                             
[13] "timebodygyroscope-mean-y"                              "timebodygyroscope-mean-z"                             
[15] "timebodygyroscopejerk-mean-x"                          "timebodygyroscopejerk-mean-y"                         
[17] "timebodygyroscopejerk-mean-z"                          "timebodyaccelerometermagnitude-mean"                  
[19] "timegravityaccelerometermagnitude-mean"                "timebodyaccelerometerjerkmagnitude-mean"              
[21] "timebodygyroscopemagnitude-mean"                       "timebodygyroscopejerkmagnitude-mean"                  
[23] "frequencybodyaccelerometer-mean-x"                     "frequencybodyaccelerometer-mean-y"                    
[25] "frequencybodyaccelerometer-mean-z"                     "frequencybodyaccelerometer-meanfrequency-x"           
[27] "frequencybodyaccelerometer-meanfrequency-y"            "frequencybodyaccelerometer-meanfrequency-z"           
[29] "frequencybodyaccelerometerjerk-mean-x"                 "frequencybodyaccelerometerjerk-mean-y"                
[31] "frequencybodyaccelerometerjerk-mean-z"                 "frequencybodyaccelerometerjerk-meanfrequency-x"       
[33] "frequencybodyaccelerometerjerk-meanfrequency-y"        "frequencybodyaccelerometerjerk-meanfrequency-z"       
[35] "frequencybodygyroscope-mean-x"                         "frequencybodygyroscope-mean-y"                        
[37] "frequencybodygyroscope-mean-z"                         "frequencybodygyroscope-meanfrequency-x"               
[39] "frequencybodygyroscope-meanfrequency-y"                "frequencybodygyroscope-meanfrequency-z"               
[41] "frequencybodyaccelerometermagnitude-mean"              "frequencybodyaccelerometermagnitude-meanfrequency"    
[43] "frequencybodyaccelerometerjerkmagnitude-mean"          "frequencybodyaccelerometerjerkmagnitude-meanfrequency"
[45] "frequencybodygyroscopemagnitude-mean"                  "frequencybodygyroscopemagnitude-meanfrequency"        
[47] "frequencybodygyroscopejerkmagnitude-mean"              "frequencybodygyroscopejerkmagnitude-meanfrequency"    
[49] "angle-timebodyaccelerometermean-gravity"               "angle-timebodyaccelerometerjerkmean-gravitymean"      
[51] "angle-timebodygyroscopemean-gravitymean"               "angle-timebodygyroscopejerkmean-gravitymean"          
[53] "angle-x-gravitymean"                                   "angle-y-gravitymean"                                  
[55] "angle-z-gravitymean"                                   "timebodyaccelerometer-std-x"                          
[57] "timebodyaccelerometer-std-y"                           "timebodyaccelerometer-std-z"                          
[59] "timegravityaccelerometer-std-x"                        "timegravityaccelerometer-std-y"                       
[61] "timegravityaccelerometer-std-z"                        "timebodyaccelerometerjerk-std-x"                      
[63] "timebodyaccelerometerjerk-std-y"                       "timebodyaccelerometerjerk-std-z"                      
[65] "timebodygyroscope-std-x"                               "timebodygyroscope-std-y"                              
[67] "timebodygyroscope-std-z"                               "timebodygyroscopejerk-std-x"                          
[69] "timebodygyroscopejerk-std-y"                           "timebodygyroscopejerk-std-z"                          
[71] "timebodyaccelerometermagnitude-std"                    "timegravityaccelerometermagnitude-std"                
[73] "timebodyaccelerometerjerkmagnitude-std"                "timebodygyroscopemagnitude-std"                       
[75] "timebodygyroscopejerkmagnitude-std"                    "frequencybodyaccelerometer-std-x"                     
[77] "frequencybodyaccelerometer-std-y"                      "frequencybodyaccelerometer-std-z"                     
[79] "frequencybodyaccelerometerjerk-std-x"                  "frequencybodyaccelerometerjerk-std-y"                 
[81] "frequencybodyaccelerometerjerk-std-z"                  "frequencybodygyroscope-std-x"                         
[83] "frequencybodygyroscope-std-y"                          "frequencybodygyroscope-std-z"                         
[85] "frequencybodyaccelerometermagnitude-std"               "frequencybodyaccelerometerjerkmagnitude-std"          
[87] "frequencybodygyroscopemagnitude-std"                   "frequencybodygyroscopejerkmagnitude-std"              